package org.example.gui.localization;

import java.util.HashMap;
import java.util.Map;

public class GuiResources {
    private static final Map<GuiLocale, Map<String, String>> DATA = new HashMap<>();

    static {
        Map<String, String> ru = new HashMap<>();
        ru.put("app.title", "LabWork Manager");

        ru.put("login.title", "Вход в систему");
        ru.put("login.login", "Логин:");
        ru.put("login.password", "Пароль:");
        ru.put("login.button", "Войти");
        ru.put("login.register", "Зарегистрироваться");
        ru.put("login.language", "Язык:");
        ru.put("login.empty", "Введите логин и пароль");
        ru.put("login.connection.error", "Ошибка подключения к серверу");
        ru.put("server.invalid.credentials", "Неверный логин или пароль");
        ru.put("server.login.success", "Вход выполнен успешно");

        ru.put("register.title", "Регистрация");
        ru.put("register.repeat.password", "Повторите пароль:");
        ru.put("register.button", "Зарегистрироваться");
        ru.put("register.cancel", "Отмена");
        ru.put("register.empty", "Заполните все поля");
        ru.put("register.passwords.not.match", "Пароли не совпадают");
        ru.put("register.success", "Регистрация выполнена успешно");

        ru.put("main.user", "Пользователь:");
        ru.put("main.language", "Язык:");
        ru.put("main.filter", "Фильтр по любой колонке:");
        ru.put("main.clear.filter", "Очистить");
        ru.put("main.sort", "Сортировать по:");
        ru.put("main.asc", "По возрастанию");
        ru.put("main.desc", "По убыванию");
        ru.put("main.apply", "Применить");
        ru.put("main.table.title", "Таблица объектов");
        ru.put("visualization.owners", "Владельцы объектов");
        ru.put("visualization.owner.id", "ID владельца");

        ru.put("button.add", "Добавить");
        ru.put("button.add.if.max", "Добавить если макс");
        ru.put("button.add.if.min", "Добавить если мин");
        ru.put("button.update", "Обновить по ID");
        ru.put("button.remove", "Удалить по ID");
        ru.put("button.remove.all", "Удалить всё");
        ru.put("button.show", "Показать все");
        ru.put("button.refresh", "Обновить");
        ru.put("button.clear", "Очистить");
        ru.put("button.filter.discipline", "Фильтр по дисциплине");
        ru.put("button.filter.name", "Фильтр начинается с");
        ru.put("button.history", "История");
        ru.put("button.save.history", "Сохранить историю");
        ru.put("button.script", "Выполнить скрипт");
        ru.put("button.info", "Информация");
        ru.put("button.object.info", "Объект");
        ru.put("button.help", "Справка");
        ru.put("button.exit", "Выход");
        ru.put("button.save", "Сохранить");
        ru.put("button.cancel", "Отмена");
        ru.put("button.close", "Закрыть");
        ru.put("main.visualization.title", "Визуализация объектов");

        ru.put("column.id", "ID");
        ru.put("column.name", "Название");
        ru.put("column.x", "X");
        ru.put("column.y", "Y");
        ru.put("column.minimal.point", "Мин. балл");
        ru.put("column.difficulty", "Сложность");
        ru.put("column.discipline", "Дисциплина");
        ru.put("column.labs.count", "Кол-во лаб.");
        ru.put("column.owner.id", "Владелец ID");
        ru.put("column.creation.date", "Дата создания");

        ru.put("dialog.add.title", "Добавление объекта");
        ru.put("dialog.edit.title", "Редактирование объекта");
        ru.put("dialog.object.info.title", "Информация об объекте");
        ru.put("dialog.collection.info.title", "Информация о коллекции");

        ru.put("field.name", "Название:");
        ru.put("field.x", "Координата X:");
        ru.put("field.y", "Координата Y:");
        ru.put("field.minimal.point", "Минимальный балл:");
        ru.put("field.difficulty", "Сложность:");
        ru.put("field.discipline", "Дисциплина:");
        ru.put("field.labs.count", "Количество лабораторных:");
        ru.put("field.owner.id", "Владелец ID:");
        ru.put("field.creation.date", "Дата создания:");

        ru.put("message.select.object", "Выберите объект в таблице");
        ru.put("message.fill.all", "Заполните все поля");
        ru.put("message.number.error", "Проверьте числовые поля");
        ru.put("message.confirm.remove", "Удалить выбранный объект?");
        ru.put("message.confirm.clear", "Очистить свои объекты?");
        ru.put("message.error.refresh", "Ошибка обновления коллекции");
        ru.put("password_requirements", "Требования к паролю:");
        ru.put("password_rule_1", "• не менее 4 символов");
        ru.put("password_rule_2", "• логин не менее 3 символов");
        ru.put("password_rule_3", "• пароль не должен быть пустым");
        ru.put("server.login.error", "Ошибка: логин должен содержать не менее 3 символов");
        ru.put("dialog.success.title", "Успех");
        ru.put("server.timeout.error", "Время ожидания ответа истекло");
        ru.put("server.password.error", "Ошибка: пароль должен содержать не менее 4 символов");

        ru.put("server.object.not.max", "Элемент не добавлен: он не является максимальным");
        ru.put("server.object.not.min", "Элемент не добавлен: он не является минимальным");
        ru.put("server.object.updated.by.id", "Элемент с ID %s успешно обновлен");
        ru.put("server.object.removed.by.id", "Элемент с ID %s успешно удален");
        ru.put("server.object.not.found.or.access", "Элемент с ID %s не найден или у вас нет прав");
        ru.put("server.objects.removed.count", "Удалено элементов: %s");
        ru.put("server.collection.cleared.count", "Ваши элементы удалены: %s шт");
        ru.put("server.filter.discipline.not.found", "Элементы с дисциплиной '%s' не найдены");
        ru.put("server.filter.prefix.not.found", "Элементы, начинающиеся с '%s', не найдены");
        ru.put("server.db.save.error", "Ошибка сохранения в базе данных");
        ru.put("server.error.invalid.id", "Ошибка: неправильный формат ID");
        ru.put("server.error.invalid.number", "Ошибка: неправильный формат числа");
        ru.put("server.error.no.discipline", "Ошибка: не указано название дисциплины");
        ru.put("server.error.no.prefix", "Ошибка: не указан префикс");
        ru.put("server.error.empty.input", "Ошибка: ввод не может быть пустым");
        ru.put("server.error.io", "Ошибка ввода-вывода");
        ru.put("main.snowfall", "Снегопад");
        ru.put("server.no.response", "Нет ответа от сервера");
        ru.put("server.empty.response", "Пустой ответ от сервера");
        ru.put("server.generic.success", "Операция выполнена успешно");
        ru.put("server.generic.error", "Произошла ошибка");
        ru.put("server.connection.error", "Ошибка подключения к серверу");
        ru.put("server.empty.collection", "Коллекция пуста");
        ru.put("server.user.registered", "Пользователь успешно зарегистрирован");
        ru.put("server.user.exists", "Пользователь с таким логином уже существует");
        ru.put("server.user.not.found", "Пользователь не найден");
        ru.put("server.invalid.password", "Неверный пароль");
        ru.put("server.database.error", "Ошибка базы данных");
        ru.put("server.collection.cleared", "Коллекция очищена");
        ru.put("server.object.added", "Объект успешно добавлен");
        ru.put("server.object.added.success", "Объект успешно добавлен");
        ru.put("server.object.updated", "Объект успешно обновлен");
        ru.put("server.object.removed", "Объект успешно удален");
        ru.put("server.script.executed", "Скрипт успешно выполнен");
        ru.put("server.object.not.found", "Объект не найден");
        ru.put("server.access.denied", "Доступ запрещен");
        ru.put("server.validation.error", "Ошибка валидации");
        ru.put("server.show.success", "Коллекция загружена");
        ru.put("server.info.success", "Информация о коллекции");
        ru.put("server.help.success", "Справка загружена");
        ru.put("server.history.success", "История команд");
        ru.put("server.filter.no.results", "По запросу '%s' ничего не найдено");
        ru.put("server.filter.results", "Найдено %d элементов по запросу '%s'");
        ru.put("validation.minimal.point.positive", "Минимальный балл должен быть больше 0");
        ru.put("validation.labs.count.positive", "Количество лабораторных должно быть больше 0");
        ru.put("dialog.enter.discipline.name", "Поиск по дисциплине");
        ru.put("dialog.enter.name.start", "Поиск по началу названия");
        ru.put("dialog.select.script.file", "Выбор файла скрипта");
        ru.put("dialog.enter.minimal.point", "Введите минимальный балл");
        DATA.put(GuiLocale.RU, ru);

        Map<String, String> be = new HashMap<>(ru);
        be.put("main.snowfall", "Снегапад");
        be.put("app.title", "LabWork Manager");
        be.put("server.timeout.error", "Час чакання ад сервера скончыўся");
        be.put("server.password.error", "Памылка: пароль павінен утрымліваць не менш за 4 сімвалы");
        be.put("server.login.error", "Памылка: лагін павінен утрымліваць не менш за 3 сімвалы");
        be.put("login.title", "Уваход у сістэму");
        be.put("login.login", "Лагін:");
        be.put("login.password", "Пароль:");
        be.put("login.button", "Увайсці");
        be.put("login.register", "Зарэгістравацца");
        be.put("login.language", "Мова:");
        be.put("login.empty", "Увядзіце лагін і пароль");
        be.put("login.connection.error", "Памылка падключэння да сервера");
        be.put("server.invalid.credentials", "Няправільны лагін або пароль");
        be.put("server.login.success", "Уваход выкананы паспяхова");

        be.put("register.title", "Рэгістрацыя");
        be.put("register.repeat.password", "Паўтарыце пароль:");
        be.put("register.button", "Зарэгістравацца");
        be.put("register.cancel", "Адмена");
        be.put("register.empty", "Запоўніце ўсе палі");
        be.put("register.passwords.not.match", "Паролі не супадаюць");
        be.put("register.success", "Рэгістрацыя выканана паспяхова");

        be.put("main.user", "Карыстальнік:");
        be.put("main.language", "Мова:");
        be.put("main.filter", "Фільтр па любым слупку:");
        be.put("main.clear.filter", "Ачысціць");
        be.put("main.sort", "Сартаваць па:");
        be.put("main.asc", "Па ўзрастанні");
        be.put("main.desc", "Па змяншэнні");
        be.put("main.apply", "Прымяніць");
        be.put("main.table.title", "Табліца аб'ектаў");
        be.put("main.visualization.title", "Візуалізацыя аб'ектаў");
        be.put("visualization.owners", "Уладальнікі аб'ектаў");
        be.put("visualization.owner.id", "ID уладальніка");

        be.put("button.add", "Дадаць");
        be.put("button.add.if.max", "Дадаць калі макс");
        be.put("button.add.if.min", "Дадаць калі мін");
        be.put("button.update", "Абнавіць па ID");
        be.put("button.remove", "Выдаліць па ID");
        be.put("button.remove.all", "Выдаліць усё");
        be.put("button.show", "Паказаць усе");
        be.put("button.refresh", "Абнавіць");
        be.put("button.clear", "Ачысціць");
        be.put("button.filter.discipline", "Фільтр па дысцыпліне");
        be.put("button.filter.name", "Фільтр пачынаецца з");
        be.put("button.history", "Гісторыя");
        be.put("button.save.history", "Захаваць гісторыю");
        be.put("button.script", "Выканаць скрыпт");
        be.put("button.info", "Інфармацыя");
        be.put("button.object.info", "Аб'ект");
        be.put("button.help", "Даведка");
        be.put("button.exit", "Выхад");
        be.put("button.save", "Захаваць");
        be.put("button.cancel", "Адмена");
        be.put("button.close", "Закрыць");

        be.put("column.id", "ID");
        be.put("column.name", "Назва");
        be.put("column.x", "X");
        be.put("column.y", "Y");
        be.put("column.minimal.point", "Мін. бал");
        be.put("column.difficulty", "Складанасць");
        be.put("column.discipline", "Дысцыпліна");
        be.put("column.labs.count", "Колькасць лаб.");
        be.put("column.owner.id", "Уладальнік ID");
        be.put("column.creation.date", "Дата стварэння");

        be.put("dialog.add.title", "Даданне аб'екта");
        be.put("dialog.edit.title", "Рэдагаванне аб'екта");
        be.put("dialog.object.info.title", "Інфармацыя аб аб'екце");
        be.put("dialog.collection.info.title", "Інфармацыя аб калекцыі");

        be.put("field.name", "Назва:");
        be.put("field.x", "Каардыната X:");
        be.put("field.y", "Каардыната Y:");
        be.put("field.minimal.point", "Мінімальны бал:");
        be.put("field.difficulty", "Складанасць:");
        be.put("field.discipline", "Дысцыпліна:");
        be.put("field.labs.count", "Колькасць лабараторных:");
        be.put("field.owner.id", "Уладальнік ID:");
        be.put("field.creation.date", "Дата стварэння:");

        be.put("message.select.object", "Выберыце аб'ект у табліцы");
        be.put("message.fill.all", "Запоўніце ўсе палі");
        be.put("message.number.error", "Праверце лікавыя палі");
        be.put("message.confirm.remove", "Выдаліць выбраны аб'ект?");
        be.put("message.confirm.clear", "Ачысціць свае аб'екты?");
        be.put("message.error.refresh", "Памылка абнаўлення калекцыі");
        be.put("password_requirements", "Патрабаванні да пароля:");
        be.put("password_rule_1", "• не менш за 4 сімвалы");
        be.put("password_rule_2", "• лагін не менш за 3 сімвалы");
        be.put("password_rule_3", "• пароль не павінен быць пустым");
        be.put("dialog.success.title", "Поспех");
        be.put("server.object.not.max", "Элемент не дададзены: ён не з'яўляецца максімальным");
        be.put("server.object.not.min", "Элемент не дададзены: ён не з'яўляецца мінімальным");
        be.put("server.object.updated.by.id", "Элемент з ID %s паспяхова абноўлены");
        be.put("server.object.removed.by.id", "Элемент з ID %s паспяхова выдалены");
        be.put("server.object.not.found.or.access", "Элемент з ID %s не знойдзены або ў вас няма правоў");
        be.put("server.objects.removed.count", "Выдалена элементаў: %s");
        be.put("server.collection.cleared.count", "Вашы элементы выдалены: %s шт");
        be.put("server.filter.discipline.not.found", "Элементы з дысцыплінай '%s' не знойдзены");
        be.put("server.filter.prefix.not.found", "Элементы, якія пачынаюцца з '%s', не знойдзены");
        be.put("server.db.save.error", "Памылка захавання ў базе даных");
        be.put("server.error.invalid.id", "Памылка: няправільны фармат ID");
        be.put("server.error.invalid.number", "Памылка: няправільны фармат ліку");
        be.put("server.error.no.discipline", "Памылка: не пазначана назва дысцыпліны");
        be.put("server.error.no.prefix", "Памылка: не пазначаны прэфікс");
        be.put("server.error.empty.input", "Памылка: увод не можа быць пустым");
        be.put("server.error.io", "Памылка ўводу-вываду");
        be.put("server.no.response", "Няма адказу ад сервера");
        be.put("server.empty.response", "Пусты адказ ад сервера");
        be.put("server.generic.success", "Аперацыя выканана паспяхова");
        be.put("server.generic.error", "Адбылася памылка");
        be.put("server.connection.error", "Памылка падключэння да сервера");
        be.put("server.empty.collection", "Калекцыя пустая");
        be.put("server.user.registered", "Карыстальнік паспяхова зарэгістраваны");
        be.put("server.user.exists", "Карыстальнік з такім лагінам ужо існуе");
        be.put("server.user.not.found", "Карыстальнік не знойдзены");
        be.put("server.invalid.password", "Няправільны пароль");
        be.put("server.database.error", "Памылка базы даных");
        be.put("server.collection.cleared", "Калекцыя ачышчана");
        be.put("server.object.added", "Аб'ект паспяхова дададзены");
        be.put("server.object.added.success", "Аб'ект паспяхова дададзены");
        be.put("server.object.updated", "Аб'ект паспяхова абноўлены");
        be.put("server.object.removed", "Аб'ект паспяхова выдалены");
        be.put("server.script.executed", "Скрыпт паспяхова выкананы");
        be.put("server.object.not.found", "Аб'ект не знойдзены");
        be.put("server.access.denied", "Доступ забаронены");
        be.put("server.validation.error", "Памылка валідацыі");
        be.put("server.show.success", "Калекцыя загружана");
        be.put("server.info.success", "Інфармацыя аб калекцыі");
        be.put("server.help.success", "Даведка загружана");
        be.put("server.history.success", "Гісторыя каманд");
        be.put("server.filter.no.results", "Па запыту '%s' нічога не знойдзена");
        be.put("server.filter.results", "Знойдзена %d элементаў па запыту '%s'");
        be.put("validation.minimal.point.positive", "Мінімальны бал павінен быць больш за 0");
        be.put("validation.labs.count.positive", "Колькасць лабараторных павінна быць больш за 0");
        be.put("dialog.enter.discipline.name", "Пошук па дысцыпліне");
        be.put("dialog.enter.name.start", "Пошук па пачатку назвы");
        be.put("dialog.select.script.file", "Выбар файла скрыпта");
        be.put("dialog.enter.minimal.point", "Увядзіце мінімальны бал");
        DATA.put(GuiLocale.BE, be);

        Map<String, String> lv = new HashMap<>();
        lv.put("main.snowfall", "Sniegputenis");
        lv.put("app.title", "LabWork Manager");
        lv.put("server.timeout.error", "Servera gaidīšanas laiks ir beidzies");
        lv.put("server.password.error", "Kļūda: parolei jāsatur vismaz 4 rakstzīmes");
        lv.put("server.login.error", "Kļūda: lietotājvārdam jāsatur vismaz 3 rakstzīmes");
        lv.put("login.title", "Pieteikšanās sistēmā");
        lv.put("login.login", "Lietotājvārds:");
        lv.put("login.password", "Parole:");
        lv.put("login.button", "Pieteikties");
        lv.put("login.register", "Reģistrēties");
        lv.put("login.language", "Valoda:");
        lv.put("login.empty", "Ievadiet lietotājvārdu un paroli");
        lv.put("login.connection.error", "Savienojuma kļūda ar serveri");
        lv.put("server.invalid.credentials", "Nepareizs lietotājvārds vai parole");
        lv.put("server.login.success", "Pieteikšanās veiksmīga");

        lv.put("register.title", "Reģistrācija");
        lv.put("register.repeat.password", "Atkārtojiet paroli:");
        lv.put("register.button", "Reģistrēties");
        lv.put("register.cancel", "Atcelt");
        lv.put("register.empty", "Aizpildiet visus laukus");
        lv.put("register.passwords.not.match", "Paroles nesakrīt");
        lv.put("register.success", "Reģistrācija veiksmīgi pabeigta");

        lv.put("main.user", "Lietotājs:");
        lv.put("main.language", "Valoda:");
        lv.put("main.filter", "Filtrs pēc jebkuras kolonnas:");
        lv.put("main.clear.filter", "Notīrīt");
        lv.put("main.sort", "Kārtot pēc:");
        lv.put("main.asc", "Augošā secībā");
        lv.put("main.desc", "Dilstošā secībā");
        lv.put("main.apply", "Pielietot");
        lv.put("main.table.title", "Objektu tabula");
        lv.put("main.visualization.title", "Objektu vizualizācija");
        lv.put("visualization.owners", "Objektu īpašnieki");
        lv.put("visualization.owner.id", "Īpašnieka ID");

        lv.put("button.add", "Pievienot");
        lv.put("button.add.if.max", "Pievienot ja maks");
        lv.put("button.add.if.min", "Pievienot ja min");
        lv.put("button.update", "Atjaunināt pēc ID");
        lv.put("button.remove", "Dzēst pēc ID");
        lv.put("button.remove.all", "Dzēst visu");
        lv.put("button.show", "Rādīt visus");
        lv.put("button.refresh", "Atjaunināt");
        lv.put("button.clear", "Notīrīt");
        lv.put("button.filter.discipline", "Filtrs pēc disciplīnas");
        lv.put("button.filter.name", "Filtrs sākas ar");
        lv.put("button.history", "Vēsture");
        lv.put("button.save.history", "Saglabāt vēsturi");
        lv.put("button.script", "Izpildīt skriptu");
        lv.put("button.info", "Informācija");
        lv.put("button.object.info", "Objekts");
        lv.put("button.help", "Palīdzība");
        lv.put("button.exit", "Iziet");
        lv.put("button.save", "Saglabāt");
        lv.put("button.cancel", "Atcelt");
        lv.put("button.close", "Aizvērt");

        lv.put("column.id", "ID");
        lv.put("column.name", "Nosaukums");
        lv.put("column.x", "X");
        lv.put("column.y", "Y");
        lv.put("column.minimal.point", "Min. punkts");
        lv.put("column.difficulty", "Grūtības pakāpe");
        lv.put("column.discipline", "Disciplīna");
        lv.put("column.labs.count", "Lab. skaits");
        lv.put("column.owner.id", "Īpašnieka ID");
        lv.put("column.creation.date", "Izveides datums");

        lv.put("dialog.add.title", "Objekta pievienošana");
        lv.put("dialog.edit.title", "Objekta rediģēšana");
        lv.put("dialog.object.info.title", "Informācija par objektu");
        lv.put("dialog.collection.info.title", "Informācija par kolekciju");

        lv.put("field.name", "Nosaukums:");
        lv.put("field.x", "Koordināta X:");
        lv.put("field.y", "Koordināta Y:");
        lv.put("field.minimal.point", "Minimālais punkts:");
        lv.put("field.difficulty", "Grūtības pakāpe:");
        lv.put("field.discipline", "Disciplīna:");
        lv.put("field.labs.count", "Laboratorijas darbu skaits:");
        lv.put("field.owner.id", "Īpašnieka ID:");
        lv.put("field.creation.date", "Izveides datums:");

        lv.put("message.select.object", "Izvēlieties objektu tabulā");
        lv.put("message.fill.all", "Aizpildiet visus laukus");
        lv.put("message.number.error", "Pārbaudiet skaitliskos laukus");
        lv.put("message.confirm.remove", "Dzēst izvēlēto objektu?");
        lv.put("message.confirm.clear", "Notīrīt savus objektus?");
        lv.put("message.error.refresh", "Kolekcijas atjaunināšanas kļūda");
        lv.put("password_requirements", "Paroles prasības:");
        lv.put("password_rule_1", "• vismaz 4 rakstzīmes");
        lv.put("password_rule_2", "• lietotājvārds vismaz 3 rakstzīmes");
        lv.put("password_rule_3", "• parole nedrīkst būt tukša");
        lv.put("dialog.success.title", "Panākumi");

        lv.put("server.object.not.max", "Objekts nav pievienots: tas nav maksimāls");
        lv.put("server.object.not.min", "Objekts nav pievienots: tas nav minimāls");
        lv.put("server.object.updated.by.id", "Objekts ar ID %s veiksmīgi atjaunināts");
        lv.put("server.object.removed.by.id", "Objekts ar ID %s veiksmīgi dzēsts");
        lv.put("server.object.not.found.or.access", "Objekts ar ID %s nav atrasts vai jums nav tiesību");
        lv.put("server.objects.removed.count", "Dzēstie objekti: %s");
        lv.put("server.collection.cleared.count", "Jūsu objekti dzēsti: %s gab");
        lv.put("server.filter.discipline.not.found", "Objekti ar disciplīnu '%s' nav atrasti");
        lv.put("server.filter.prefix.not.found", "Objekti, kas sākas ar '%s', nav atrasti");
        lv.put("server.db.save.error", "Kļūda saglabāšanā datubāzē");
        lv.put("server.error.invalid.id", "Kļūda: nepareizs ID formāts");
        lv.put("server.error.invalid.number", "Kļūda: nepareizs skaitļa formāts");
        lv.put("server.error.no.discipline", "Kļūda: nav norādīts disciplīnas nosaukums");
        lv.put("server.error.no.prefix", "Kļūda: nav norādīts prefikss");
        lv.put("server.error.empty.input", "Kļūda: ievade nevar būt tukša");
        lv.put("server.error.io", "Ievades/izvades kļūda");
        lv.put("validation.minimal.point.positive", "Minimālajam punktam jābūt lielākam par 0");
        lv.put("validation.labs.count.positive", "Laboratorijas darbu skaitam jābūt lielākam par 0");
        lv.put("dialog.enter.discipline.name", "Meklēšana pēc disciplīnas");
        lv.put("dialog.enter.name.start", "Meklēšana pēc nosaukuma sākuma");
        lv.put("dialog.select.script.file", "Skripta faila izvēle");
        lv.put("dialog.enter.minimal.point", "Ievadiet minimālo punktu skaitu");
        DATA.put(GuiLocale.LV, lv);

        Map<String, String> en = new HashMap<>();
        en.put("main.snowfall", "Snowfall");
        en.put("app.title", "LabWork Manager");
        en.put("server.timeout.error", "Server timeout has expired");
        en.put("server.password.error", "Error: password must contain at least 4 characters");

        en.put("login.title", "Sign in");
        en.put("login.login", "Login:");
        en.put("login.password", "Password:");
        en.put("server.login.error", "Error: login must contain at least 3 characters");
        en.put("login.button", "Sign in");
        en.put("login.register", "Register");
        en.put("login.language", "Language:");
        en.put("login.empty", "Enter login and password");
        en.put("login.connection.error", "Server connection error");
        en.put("server.invalid.credentials", "Invalid login or password");
        en.put("server.login.success", "Login successful");

        en.put("register.title", "Registration");
        en.put("register.repeat.password", "Repeat password:");
        en.put("register.button", "Register");
        en.put("register.cancel", "Cancel");
        en.put("register.empty", "Fill in all fields");
        en.put("register.passwords.not.match", "Passwords do not match");
        en.put("register.success", "Registration completed successfully");

        en.put("main.user", "User:");
        en.put("main.language", "Language:");
        en.put("main.filter", "Filter by any column:");
        en.put("main.clear.filter", "Clear");
        en.put("main.sort", "Sort by:");
        en.put("main.asc", "Ascending");
        en.put("main.desc", "Descending");
        en.put("main.apply", "Apply");
        en.put("main.table.title", "Objects table");
        en.put("main.visualization.title", "Objects visualization");
        en.put("visualization.owners", "Object Owners");
        en.put("visualization.owner.id", "Owner ID");

        en.put("button.add", "Add");
        en.put("button.add.if.max", "Add if max");
        en.put("button.add.if.min", "Add if min");
        en.put("button.update", "Update by ID");
        en.put("button.remove", "Remove by ID");
        en.put("button.remove.all", "Remove all");
        en.put("button.show", "Show all");
        en.put("button.refresh", "Refresh");
        en.put("button.clear", "Clear");
        en.put("button.filter.discipline", "Filter by discipline");
        en.put("button.filter.name", "Filter starts with");
        en.put("button.history", "History");
        en.put("button.save.history", "Save history");
        en.put("button.script", "Execute script");
        en.put("button.info", "Info");
        en.put("button.object.info", "Object");
        en.put("button.help", "Help");
        en.put("button.exit", "Exit");
        en.put("button.save", "Save");
        en.put("button.cancel", "Cancel");
        en.put("button.close", "Close");

        en.put("column.id", "ID");
        en.put("column.name", "Name");
        en.put("column.x", "X");
        en.put("column.y", "Y");
        en.put("column.minimal.point", "Minimal point");
        en.put("column.difficulty", "Difficulty");
        en.put("column.discipline", "Discipline");
        en.put("column.labs.count", "Labs count");
        en.put("column.owner.id", "Owner ID");
        en.put("column.creation.date", "Creation date");

        en.put("dialog.add.title", "Add object");
        en.put("dialog.edit.title", "Edit object");
        en.put("dialog.object.info.title", "Object information");
        en.put("dialog.collection.info.title", "Collection information");

        en.put("field.name", "Name:");
        en.put("field.x", "Coordinate X:");
        en.put("field.y", "Coordinate Y:");
        en.put("field.minimal.point", "Minimal point:");
        en.put("field.difficulty", "Difficulty:");
        en.put("field.discipline", "Discipline:");
        en.put("field.labs.count", "Labs count:");
        en.put("field.owner.id", "Owner ID:");
        en.put("field.creation.date", "Creation date:");

        en.put("message.select.object", "Select an object in the table");
        en.put("message.fill.all", "Fill in all fields");
        en.put("message.number.error", "Check numeric fields");
        en.put("message.confirm.remove", "Remove selected object?");
        en.put("message.confirm.clear", "Clear your objects?");
        en.put("message.error.refresh", "Collection refresh error");
        en.put("password_requirements", "Password requirements:");
        en.put("password_rule_1", "• at least 4 characters");
        en.put("password_rule_2", "• username must be at least 3 characters");
        en.put("password_rule_3", "• password must not be empty");
        en.put("dialog.success.title", "Success");

        en.put("server.object.not.max", "Object not added: it is not maximum");
        en.put("server.object.not.min", "Object not added: it is not minimum");
        en.put("server.object.updated.by.id", "Object with ID %s updated successfully");
        en.put("server.object.removed.by.id", "Object with ID %s removed successfully");
        en.put("server.object.not.found.or.access", "Object with ID %s not found or you don't have permission");
        en.put("server.objects.removed.count", "Objects removed: %s");
        en.put("server.collection.cleared.count", "Your objects deleted: %s pcs");
        en.put("server.filter.discipline.not.found", "Objects with discipline '%s' not found");
        en.put("server.filter.prefix.not.found", "Objects starting with '%s' not found");
        en.put("server.db.save.error", "Database save error");
        en.put("server.error.invalid.id", "Error: invalid ID format");
        en.put("server.error.invalid.number", "Error: invalid number format");
        en.put("server.error.no.discipline", "Error: discipline name not specified");
        en.put("server.error.no.prefix", "Error: prefix not specified");
        en.put("server.error.empty.input", "Error: input cannot be empty");
        en.put("server.error.io", "I/O error");
        en.put("server.no.response", "No response from server");
        en.put("server.empty.response", "Empty response from server");
        en.put("server.generic.success", "Operation completed successfully");
        en.put("server.generic.error", "An error occurred");
        en.put("server.connection.error", "Server connection error");
        en.put("server.empty.collection", "Collection is empty");
        en.put("server.user.registered", "User registered successfully");
        en.put("server.user.exists", "User with this login already exists");
        en.put("server.user.not.found", "User not found");
        en.put("server.invalid.password", "Invalid password");
        en.put("server.database.error", "Database error");
        en.put("server.collection.cleared", "Collection cleared");
        en.put("server.object.added", "Object added successfully");
        en.put("server.object.added.success", "Object added successfully");
        en.put("server.object.updated", "Object updated successfully");
        en.put("server.object.removed", "Object removed successfully");
        en.put("server.script.executed", "Script executed successfully");
        en.put("server.object.not.found", "Object not found");
        en.put("server.access.denied", "Access denied");
        en.put("server.validation.error", "Validation error");
        en.put("server.show.success", "Collection loaded");
        en.put("server.info.success", "Collection information");
        en.put("server.help.success", "Help loaded");
        en.put("server.history.success", "Command history");
        en.put("server.filter.no.results", "No results found for '%s'");
        en.put("server.filter.results", "Found %d elements for '%s'");
        en.put("validation.minimal.point.positive", "Minimal point must be greater than 0");
        en.put("validation.labs.count.positive", "Labs count must be greater than 0");
        en.put("dialog.enter.discipline.name", "Search by Discipline");
        en.put("dialog.enter.name.start", "Search by Name Prefix");
        en.put("dialog.select.script.file", "Select Script File");
        en.put("dialog.enter.minimal.point", "Enter minimal point");
        DATA.put(GuiLocale.EN_IE, en);
    }

    public static String get(GuiLocale locale, String key) {
        Map<String, String> map = DATA.getOrDefault(locale, DATA.get(GuiLocale.RU));
        return map.getOrDefault(key, key);
    }
}